// Problem-389: Find the Difference

// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.
// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

class Solution {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char, int> letters;
        char character='\0';

        for(char c : s){
            letters[c]++;
        }

        for(char c : t){
            if(letters[c] > 0){
                letters[c]--;
            }
            else{
                character = c;
            }
        }
        return character;
    }
};